#import './NotifyItem/defaultNotificationFragment.gql'

mutation markNotificationsAsRead($ids:[ID!]!) {
    markNotificationAsRead(notifications: $ids) {
        ...defaultNotificationFragment
    }
}
