#import "./NotifyItem/defaultNotificationFragment.gql"
#import "./NotifyItem/badgeIssuedFragment.gql"
#import "./NotifyItem/badgeIssuedOnDepsFragment.gql"
#import "./NotifyItem/badgeIssueRequestFragment.gql"
#import "./NotifyItem/certificateIssueFragment.gql"
#import "./NotifyItem/evidenceCheckedFragment.gql"
#import "./NotifyItem/organisationInviteFragment.gql"
#import "./NotifyItem/projectInviteFragment.gql"
#import "./NotifyItem/readyToStartMissionFragment.gql"

subscription newNotificationCreated {
    createdNotification {
        ...defaultNotificationFragment
        ...badgeIssuedFragment
        ...badgeIssuedOnDepsFragment
        ...badgeIssueRequestFragment
        ...certificateIssueFragment
        ...evidenceCheckedFragment
        ...organisationInviteFragment
        ...projectInviteFragment
        ...readyToStartMissionFragment
    }
}
