subscription notificationBellSubscriptions($platforms: [Platform!]) {
    updatedViewer {
        id
        notifications(platforms: $platforms) {
            total
            unhandled
            unread
        }
        tasksToCheck {
            total
        }
    }
}
