mutation createUserPasswordMutation($password:String, $rePassword: String) {
    createPassword(password: $password, rePassword: $rePassword) {
        ok
        errors {
            field
            code
            parent
            type
            args {
                name
                value
            }
        }
        me {
            id
            connections {
                id
                display
                type
            }
        }
    }
}
