mutation updateUserPasswordMutation($cPassword: String!, $password:String!, $rePassword: String!) {
    changePassword(cPassword: $cPassword, password: $password, rePassword: $rePassword) {
        ok
        errors {
            field
            code
            parent
            type
            args {
                name
                value
            }
        }
        me {
            id
            connections {
                id
                display
                type
            }
        }
    }
}