query organisationVerifyStatus($id: ID!) {
    maybeOrganisation(id: $id) {
        id
        error
        organisation {
            id
            name
            verifyStatus
            perms {
                edit { value }
            }
        }
    }
}
