export default {
    home:        '/',
    afterLogout: '/?logged-out=1',
    map:         '/?view=map',

    opportunities:              '/opportunities',
    opportunitiesWithQuery:     '/opportunities?config=:config&offset=:offset',
    opportunitiesInCategory:    '/opportunities?category=:id',
    opportunitiesWithSkill:     '/opportunities?skill=:id',
    playlistEdit:               '/playlists/:id/edit',
    playlistStart:              '/playlists/:id/start',
    playlistLeave:              '/playlists/:id/leave',
    playlistCreate:             '/playlists/create',
    playlistCreateOrganisation: '/playlists/create?organisation=:id',
    playlistFinalize:           '/playlists/:id/finalize',
    playlistSearch:             '/opportunities?config=playlists',

    activityView:          '/activities/:id',
    activityViewBadgeInit: '/activities/:id/?initBadge=1',
    activityUsers:         '/activities/:id/users',
    activityUsersInvite:   '/activities/:id/users?invite=1',
    activityInvites:       '/activities/:id/invites',
    activityBadges:        '/activities/:id/badges',
    activityBadgesIssue:   '/activities/:id/badges?issueBadgeClass=:badgeClass',
    playlistActivityView:  '/activities/:playlist/part/:id',
    activityEvidences:     '/activities/:id/evidences',
    activityAttend:        '/events/:id/attend',
    activityLeave:         '/events/:id/leave',

    badges:             '/?badges',
    collections:        '/?collections',
    history:            '/?history',
    fallowedOrganisers: '/?fallowedOrganisers',
    dashboard:          '/dashboard',
    help:               '/?help',
    analytics:          '/dashboard?analytics',

    personalDashboard:              '/dashboard/me',
    personalDashboardBadges:        '/dashboard/me/badges',
    personalDashboardPlaylists:     '/dashboard/me/playlists',
    personalDashboardSettings:      '/dashboard/me/settings',
    personalDashboardSettingsNoLog: '/dashboard/me/settings?noLog=1',

    orgDashboard:             '/dashboard/:id',
    orgDashboardPlaylists:    '/dashboard/:id/playlists',
    orgDashboardAnalytics:    '/dashboard/:id/analytics',
    orgDashboardSettings:     '/dashboard/:id/settings',
    orgDashboardUsers:        '/dashboard/:id/users',
    orgDashboardUsersInvite:  '/dashboard/:id/users?invite=1',
    orgDashboardInvites:      '/dashboard/:id/invites',
    orgDashboardEndorsements: '/dashboard/:id/endorsements',

    authorize:         '/dashboard/auth',
    authorizeWithBack: '/dashboard/auth?back=:back',
    authorizeCallback: '/dashboard/auth/callback',
    health:            '/health',
    logout:            '/logout',

    spaceCreate:               '/organisers/create',
    spaceEdit:                 '/organisers/:id/edit',
    verifiedSpaces:            '/organisers',
    spaceView:                 '/organisers/:id',
    requestOrganisationVerify: '/organisers/:id/verify',

    eventCreate:             '/events/create',
    eventCreateOrganisation: '/events/create?organisation=:id',
    eventEdit:               '/events/:id/edit',

    claimByCode: '/claim',

    about:          '/about',
    partners:       '/',
    howToUse:       '/',
    blog:           '/blog',
    qa:             '/faq',
    privacy:        '/privacy',
    security:       '/security',
    termsOfService: '/terms-of-service',
    openBadges:     'https://www.badgecraft.eu/en/open-badges',
    cities:         'https://www.citiesoflearning.eu/',
    contacts:       '/contact',

    badgecraftProjectEdit: '/auto/projects/:id/edit',

    evidencesToCheck: '/evidences-to-check',
    notifications:    '/notifications',
    handleNotify:     '/notifications/:id',
    emailVerify:      '/email-verify/:token',

    badgeView:         '/badges/:id',
    personalBadgeView: '/dashboard/me/badges/:id',
    badgeClassView:    '/activities/:projectId/classes/:id',

    endorsementRequest: '/endorsements/:id',
};
