#import "./activityFragment.gql"

query activityView ($id:ID!) {
    maybeProject(id: $id) {
        id
        error
        project {
            ...activityFragment
            skills {
                id
                name
                type
            }
        }
    }
}
