query inviteEmailsToProjectInfo($id:ID!) {
    maybeProject(id: $id) {
        id
        error
        project {
            id
            name
            inviteTeams
            joinType
            joinUUID
        }
    }
}
