#import "../../Endorsement/endorsementFragment.gql"

fragment endorsementHandledFragment on EndorsementHandledNotification {
    created
    endorsement {
        ...endorsementFragment
    }
    endorsementStatus
}
