fragment organisationInviteFragment on OrganisationInviteNotification {
    organisation {
        id
        name
        picture
        perms {
            view { value }
        }
        long {
            id
            viewerTeam
        }
    }
    issuer {
        id
        displayName
    }
}
