fragment competenceReviewRequestFragment on CompetenceReviewRequest {
    id
    teams
    areas {
        id
        name
        image
    }
    created
    project {
        id
        name
    }
}
