#import "./endorsementFragment.gql"

query endorsementQuery($id:ID!) {
    maybeEndorsement(id: $id) {
        id
        error
        endorsement {
            ...endorsementFragment
        }
    }
}
