mutation updateGoalTitle($id: ID!, $value:String) {
    updateGoal(id: $id, title: $value) {
        ok
        errors {
            field
            code
            type
            parent
            args {
                name
                value
            }
        }
        goal {
            id
            title
        }
    }
}
