query footerSite {
    site {
        id
        coFundedBy {
            image
            title
        }
        footer {
            title
            links {
                title
                path
            }
        }
    }
}
